innovation/urls.py
from django.urls import include, path
from django.conf import settings
from stories.views import classroom, students, teachers
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext


urlpatterns = [
    
 
   
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns( # < here
    path('', include('stories.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', classroom.SignUpView.as_view(), name ='signup'),
    path('accounts/signup/student/', students.StudentSignUpView.as_view(), name ='student_signup'),
    path('accounts/signup/teacher/', teachers.TeacherSignUpView.as_view(), name='teacher_signup'),
    path('djrichtextfield/', include('djrichtextfield.urls')),
    
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stories/urls.py
from django.urls import include, path
from .views import classroom, students, teachers



urlpatterns = [
    path('', classroom.home, name='home'),
    path('Innovtion/', classroom.Introduction, name='Introduction'),
    path('Stories/', classroom.Stories, name='Stories'),
    path('Research/', classroom.Research, name='Research'),
    path('teachers/', include(([
        path('', teachers.TeachersListView.as_view(), name='stories_list'),
        path('studies/tables/', teachers.TableListView.as_view(), name='table_list'),
        path('comments/<int:pk>/', teachers.EvaluerlistView, name='comment_list'),
        path('case/<int:pk>/', teachers.take_quiz, name='take_quiz'),
         path('case/Remove/<int:pk>/', teachers.DeleteView, name='delete_quiz'),
        path('story/<int:pk>/', teachers.publi_quiz, name='publi_quiz'),
        path('studies/', teachers.modifaction, name='modif_quiz'),
        path('board/terms/', teachers.TermsListView.as_view(), name='terms_teacher_list'),
       
   
        

        
#<int:pk>/

    ], 'stories'), namespace='teachers')),

   path('students/', include(([    
        path('', students.HomeListView.as_view(), name='students_home'),
        path('board/', students.StudiesListView.as_view(), name='students_borad'),
        path('board/contenu', students.contenuListView.as_view(), name='students_contenu'),
        path('board/enjeu', students.enjeuListView.as_view(), name='students_enjeu'),
        path('board/comite', students.comiteListView.as_view(), name='students_comite'),
        path('board/exemple', students.exempleListView.as_view(), name='students_exemple'),
        path('board/tables/', students.TableListView.as_view(), name='table_list'),
        path('board/dates/', students.DatesListView.as_view(), name='dates_list'),
        path('board/information/', students.InfoListView.as_view(), name='info_list'),
        path('board/terms/', students.TermsListView.as_view(), name='terms_list'),
        path('case/add/', students.CaseCreateView.as_view(), name='case_add'),
        path('case/<int:pk>/change', students.CaseUpdateView.as_view(), name='case_change'),
        path('case/<int:pk>/delete/', students.QuizDeleteView.as_view(), name='case_delete'),
        path('case/<int:pk>/display', students.post_detail, name='post_detail'),
        path('case/<int:pk>/evaluation', students.evaluation_quiz, name='evalu_detail'),
        ], 'stories'), namespace='students')),

]

stories/views/classroom.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView
from django.utils import timezone
from django.utils.translation import ugettext
from ..models import Cases, Student, User, School
from  stories.filters import CasesFilter


class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


def home(request):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            return redirect('teachers:stories_list')
        else:
            return redirect('students:students_borad')
    return render(request, 'classroom/home.html')


    
def Introduction(request):
     template_name = 'classroom/Introduction.html'
     return render(request, template_name)



def Research(request):
     case_list = Cases.objects.all()
     case_filter = CasesFilter(request.GET, queryset = case_list)
     template_name = 'classroom/research.html'
     return render(request, template_name, {'filter' : case_filter})



def Stories(request):
     posts = Cases.objects.filter(created_date__lte=timezone.now()).order_by('created_date')
     return render(request, 'classroom/stories.html', {'posts':posts})

stories/views/students.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from ..decorators import student_required
from ..forms import  StudentSignUpForm, GroupForm
from ..models import Cases, Student, User, School, Comment, SummaryHistory
from django.utils.translation import ugettext
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.http import Http404



class StudentSignUpView(CreateView):
    model = User
    form_class = StudentSignUpForm
    template_name = 'registration/student_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'student'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('students:students_borad')



class HomeListView(ListView):
    model = Cases
    ordering = ('title_case', )
    context_object_name = 'cases'
    template_name = 'classroom/students/index.html'

@method_decorator([login_required, student_required], name='dispatch')
class StudiesListView(ListView):
    model = Cases
    ordering = ('title_case', )
    context_object_name = 'cases'
    template_name = 'classroom/students/board/index.html'



@method_decorator([login_required, student_required], name='dispatch')
class TableListView(ListView):
    model = Cases
    ordering = ('title_case', )
    context_object_name = 'cases'
    template_name = 'classroom/students/board/tables-basic.html'

    def get_queryset(self):
        queryset = self.request.user.cases \
            .select_related('school_case') 
        return queryset


@method_decorator([login_required, student_required], name='dispatch')
class DatesListView(ListView):
    model = School
    context_object_name = 'cases'
    template_name ='classroom/students/board/dates.html'
    
    def get_queryset(self):
        queryset = self.request.user.student.school\
            .prefetch_related('students_school') 
        return queryset


@method_decorator([login_required, student_required], name='dispatch')
class InfoListView(ListView):
    model = School
    context_object_name = 'cases'
    template_name ='classroom/students/board/information.html'
    
 
@method_decorator([login_required, student_required], name='dispatch')
class TermsListView(ListView):
    model = School
    context_object_name = 'cases'
    template_name ='classroom/students/board/terms.html'



@method_decorator([login_required, student_required], name='dispatch')
class CaseCreateView(CreateView):
    model = Cases
    fields = ('title_case', 'subject',  'produit', 'mois', 'image_produit', 'date', 'context', 'context_images', 'description', 'description_shema',  'diagnostic',  'diagnostic_shema',  'processus',  'processus_shema',  'reference', 'abstract', 'auteur', 'school_case', 'terms_and_conditions')
    template_name = 'classroom/students/board/forms-basic.html'
    #case_add_form

    def form_valid(self, form):
        case = form.save(commit=False)
        case.owner = self.request.user
        case.save()
        return redirect('students:case_change', case.pk)


@method_decorator([login_required, student_required], name='dispatch')
class CaseUpdateView(UpdateView):
    model = Cases
    fields = fields = ('title_case', 'subject', 'produit', 'mois', 'image_produit', 'date', 'context', 'context_images', 'description', 'description_shema',  'diagnostic',  'diagnostic_shema',  'processus',  'processus_shema',  'reference', 'abstract', 'auteur', 'school_case', 'terms_and_conditions')
    context_object_name = 'case'
    template_name = 'classroom/students/case_change_form.html'
    
    def get_queryset(self):
        '''
        This method is an implicit object-level permission management
        This view will only match the ids of existing quizzes that belongs
        to the logged in user.
        '''
        return self.request.user.cases.all()
 
    def form_valid(self, form):
        case = form.save(commit=False)
        case.update_date = timezone.now()
        case.save()
        return redirect('students:case_change', case.pk)


        



@method_decorator([login_required, student_required], name='dispatch')
class QuizDeleteView(DeleteView):
    model = Cases
    context_object_name = 'case'
    template_name = 'classroom/students/case_delete_confirm.html'
    success_url = reverse_lazy('students:table_list')

    def delete(self, request, *args, **kwargs):
        quiz = self.get_object()
        messages.success(request, 'The quiz %s was deleted with success!' % quiz.title_case)
        return super().delete(request, *args, **kwargs)

    def get_queryset(self):
        return self.request.user.cases.all()







def post_detail(request, pk):
    post = get_object_or_404(Cases, pk=pk)
    return render(request, 'classroom/home/landing.html', {'post': post})
    
    #return render(request, 'classroom/students/case_form_display.html', {'post': post})
    


@login_required
@student_required
def evaluation_quiz(request, pk):
    try:
        quiz = get_object_or_404(Cases, pk=pk)
        Comments = Comment.objects.filter(case__pk= quiz.pk).order_by('date_comment')
    except Comment.DoesNotExist:
            raise Http404('cases does not exist')

    return render(request, 'classroom/students/board/evaluation_resultat.html', {'Comments': Comments}  )



@method_decorator([login_required, student_required], name='dispatch')
class contenuListView(ListView):
    model = Cases
    ordering = ('title_case', )
    context_object_name = 'cases'
    template_name = 'classroom/students/board/contenu.html'


@method_decorator([login_required, student_required], name='dispatch')
class enjeuListView(ListView):
    model = Cases
    ordering = ('title_case', )
    context_object_name = 'cases'
    template_name = 'classroom/students/board/enjeu.html'



@method_decorator([login_required, student_required], name='dispatch')
class comiteListView(ListView):
    model = Cases
    ordering = ('title_case', )
    context_object_name = 'cases'
    template_name = 'classroom/students/board/comite.html'




@method_decorator([login_required, student_required], name='dispatch')
class exempleListView(ListView):
    model = Cases
    ordering = ('title_case', )
    context_object_name = 'cases'
    template_name = 'classroom/students/board/exemple.html'

stories/views/teachers.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Avg, Count
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from ..decorators import teacher_required
from ..models import Cases, Teacher, School, User,  Comment, SummaryHistory, Case_publ
from django.views.generic import CreateView, ListView, UpdateView
from ..forms import  TeacherSignUpForm, CommentForm, StorieForm, pubForm
from django.http import HttpResponse
from django.template import loader
from django.http import Http404
from django.utils.translation import ugettext
from django.shortcuts import render
from django.http import HttpResponseRedirect



class TeacherSignUpView(CreateView):
    model = User
    form_class = TeacherSignUpForm
    template_name = 'registration/signup_form_teacher.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'teacher'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('teachers:stories_list')



@method_decorator([login_required, teacher_required], name='dispatch')
class TeachersListView(ListView):
    model = Cases
    ordering = ('title_case', )
    context_object_name = 'cases'
    template_name = 'classroom/teachers/board/index.html'


    

@method_decorator([login_required, teacher_required], name='dispatch')
class TermsListView(ListView):
    model = Cases
    ordering = ('title_case', )
    context_object_name = 'cases'
    template_name = 'classroom/teachers/board/terms_teacher.html'





@method_decorator([login_required, teacher_required], name='dispatch')
class TableListView(ListView):
    model = Cases
    ordering = ('title_case', )
    context_object_name = 'cases'
    template_name = 'classroom/teachers/board/tables-basic.html'

    def get_queryset(self):
        teacher = self.request.user.teacher
        teacher_schools = teacher.school.values_list('pk', flat=True)
        # taken_quizzes = student.quizzes.values_list('pk', flat=True)
        queryset = Cases.objects.filter(school_case__in = teacher_schools) 
        return queryset





@login_required
@teacher_required
def publication(request, pk):
    quiz = get_object_or_404(Cases, pk=pk)
    teacher = request.user.teacher
    template_name = 'registration/signup_form_teacher.html'


    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.case= quiz
            post.save()
            return redirect('teachers:take_quiz', quiz.pk)
  


def EvaluerlistView(request, pk):
    try:
        comment = get_object_or_404(Comment, pk=pk)
    except Comment.DoesNotExist:
            raise Http404('cases does not exist')

    return render(request, 'classroom/teachers/board/takens.html', {'comment': comment}  )


@login_required
@teacher_required
def take_quiz(request, pk):
    quiz = get_object_or_404(Cases, pk=pk)
    teacher = request.user.teacher
    template_name = 'registration/signup_form_teacher.html'

    try:

        summary_history = SummaryHistory.objects.filter(case__pk= quiz.pk).order_by('-version')
    except summary_history.DoesNotExist:
            raise Http404('cases does not exist')

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.case= quiz
            post.owner = request.user
            post.save()
            return redirect('teachers:take_quiz', quiz.pk)
    else:

        form = CommentForm()
        try:
            quiz = get_object_or_404(Cases, pk=pk)
            Comments = Comment.objects.filter(case__pk= quiz.pk).order_by('date_comment')
        except Comment.DoesNotExist:
               raise Http404('cases does not exist')

    return render(request, 'classroom/teachers/board/forms.html', {'form': form, 'quiz':quiz, 'Comments': Comments, 'summary_history': summary_history})




@login_required
@teacher_required
def modifaction(request, pk):
    try:
        quiz = get_object_or_404(Cases, pk=pk)
        summary_history = SummaryHistory.objects.filter(case__pk= quiz.pk).order_by('-version')
    except summary_history.DoesNotExist:
            raise Http404('cases does not exist')

    return render(request, 'classroom/teachers/board/tables-basic.html', {'summary_history': summary_history}  )



@method_decorator([login_required, teacher_required], name='dispatch')
class DatesListView(ListView):
    model = School
    context_object_name = 'cases'
    template_name ='classroom/teachers/board/dates.html'
    
    def get_queryset(self):
        queryset = self.request.user.teacher.school\
            .prefetch_related('teacher_school') 
        return queryset



@login_required
@teacher_required
def DeleteView(request, pk):
    try:
           quiz = get_object_or_404(Cases, pk=pk).delete()
    except quiz.DoesNotExist:
            raise Http404('cases does not exist')

    return render(request, 'classroom/teachers/board/tables-basic.html' )




@login_required
@teacher_required
def publi_quiz(request, pk):
    quiz = get_object_or_404(Cases, pk=pk)
    
    try:
           newSummary = Case_publ(case_publ=quiz)
           newSummary.save()
    except quiz.DoesNotExist:
            raise Http404('cases does not exist')

    return render(request, 'classroom/teachers/board/index.html' )






           



    

stories/templates/classroom/teachers/publier.html
{% load static %}
{% load i18n %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
<!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Teacher Board </title>
    <meta name="description" content="Sufee Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="apple-icon.png">
    <link rel="shortcut icon" href="favicon.ico">

    <link rel="stylesheet" href="{%  static 'Students/Dashboard/vendors/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{%  static 'Students/Dashboard/vendors/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{%  static 'Students/Dashboard/vendors/themify-icons/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{%  static 'Students/Dashboard/vendors/flag-icon-css/css/flag-icon.min.css' %}">
    <link rel="stylesheet" href="{%  static 'Students/Dashboard/vendors/selectFX/css/cs-skin-elastic.css' %}">
    <link rel="stylesheet" href="{%  static 'Students/Dashboard/vendors/jqvmap/dist/jqvmap.min.css '%}">
    <link rel="stylesheet" href="{%  static 'Students/Dashboard/assets/css/style.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>

</head>

<body>


    <!-- Left Panel -->

    <aside id="left-panel" class="left-panel">
        <nav class="navbar navbar-expand-sm navbar-default">

            <div class="navbar-header">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-menu" aria-controls="main-menu" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="./"><img src="" alt=" Teacher Board"></a>
                <a class="navbar-brand hidden" href="./"><img src="{%  static 'Students/Dashboard/images/logo2.png'%}" alt="Logo"></a>
            </div>

            <div id="main-menu" class="main-menu collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active">
                            <a href="{% url 'teachers:stories_list'  %}"> <i class="menu-icon fa fa-dashboard"></i>{% trans  "How it Works" %} </a>
                    </li>
                    <h3 class="menu-title">{% trans "Fonctions" %}</h3><!-- /.menu-title -->
                    <!----------------------------------------------------->
                      <!-----------------------Tables .html-->
                        <li class="menu-item-has-children dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-table"></i>Stories tracking table</a>
                        <ul class="sub-menu children dropdown-menu">
                            <li><i class="fa fa-table"></i><a href="{% url 'teachers:table_list' %}">{% trans "Case studies" %}</a></li>
                     
                        </ul>
                    </li>
         
                    
                    <!---------------------------Extra pgaes -->
                    <h3 class="menu-title">{% trans "Guidelines" %}</h3><!-- /.menu-title -->




                 
              
                  
                    <li class="menu-item-has-children dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-glass"></i>{% trans "Terms Of Use"  %}</a>
                        <ul class="sub-menu children dropdown-menu">
                            <li><i class="menu-icon fa fa-sign-in"></i><a href="{% url 'teachers:terms_teacher_list' %}">Terms and Conditions</a></li>
                    
                        </ul>
                    </li>
                     
                
                
            </div><!-- /.navbar-collapse -->
        </nav>
    </aside><!-- /#left-panel -->

    <!-- Left Panel -->

    <!-- Right Panel -->

    <div id="right-panel" class="right-panel">

        <!-- Header-->
        <header id="header" class="header">

            <div class="header-menu">

                <div class="col-sm-7">
                    <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>
                    <div class="header-left">
                        <button class="search-trigger"><i class="fa fa-search"></i></button>
                        <div class="form-inline">
                            <form class="search-form">
                                <input class="form-control mr-sm-2" type="text" placeholder="Search ..." aria-label="Search">
                                <button class="search-close" type="submit"><i class="fa fa-close"></i></button>
                            </form>
                        </div>

                        <div class="dropdown for-notification">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="notification" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-bell"></i>
                       
                            </button>
                            <div class="dropdown-menu" aria-labelledby="notification">
                             
                            
                            </div>
                        </div>

                        <div class="dropdown for-message">
                            <button class="btn btn-secondary dropdown-toggle" type="button"
                                id="message"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="ti-email"></i>
                              
                            </button>
                            <div class="dropdown-menu" aria-labelledby="message">
              
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-5">
                    <div class="user-area dropdown float-right">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {% if user.is_authenticated %}
                                <p class="nav-link"><strong>{{ user.username }}</strong></p>
                              {% else %}
                              <p class="pt-3"><strong>User</strong></p>
                              {% endif %}
                        </a>
                     
                        <div class="user-menu dropdown-menu">
                            

                            <a class="nav-link" href="{% url 'logout' %}"><i class="fa fa-power-off"></i> Logout</a>
                        </div>
                    </div>

                    <div class="language-select dropdown" id="language-select">
                        <a class="dropdown-toggle" href="#" data-toggle="dropdown"  id="language" aria-haspopup="true" aria-expanded="true">
                            <i class="flag-icon flag-icon-us"></i>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="language">
                            <div class="dropdown-item">
                                    <a class="dropdown-toggle" href="https://www.google.com/"  aria-haspopup="true" aria-expanded="true">
                                        <i class="flag-icon flag-icon-fr"></i>
                                </a>
                                
                            </div>
                            <div class="dropdown-item">
                                    <a class="dropdown-toggle" href="https://www.google.com/"  aria-haspopup="true" aria-expanded="true">
                                        <i class="flag-icon flag-icon-es"></i>
                                </a>
                                
                            </div>
                            <div class="dropdown-item">
                                    <a class="dropdown-toggle" href="https://www.google.com/"  aria-haspopup="true" aria-expanded="true">
                                        <i class="flag-icon flag-icon-us"></i>
                                </a>
                          
                            </div>
                            <div class="dropdown-item">
                                    <a class="dropdown-toggle" href="https://www.google.com/"  aria-haspopup="true" aria-expanded="true">
                                            <i class="flag-icon flag-icon-it"></i>
                                    </a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </header><!-- /header -->
        <!-- Header-->
        <!-- Header-->



        <div class="content mt-3">



            <div class="col-xl-6">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-4">
                                <h4 class="card-title mb-0">{% trans "Expert"  %}</h4>
                                <div class="small text-muted"> </div>
                            </div>
                            <!--/.col-->
           
                            <!--/.col-->
          
          
                        </div>
                        <!--/.row-->
                        <div class="chart-wrapper mt-4">
                            
                                <a >
                                    <img class="align-self-center  mr-3" style="width:700px; height:500px;" alt="" src="{%  static 'Board/assets/img/figure2.png'%}">
                                </a>
                        </div>
          
                    </div>
                 
                </div>
            </div>











            <div class="col-xl-6">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-4">
                                <h4 class="card-title mb-0">{% trans "Procedure"  %}</h4>
                                <div class="small text-muted"> </div>
                            </div>
                            <!--/.col-->
           
                            <!--/.col-->
          
          
                        </div>
                        <!--/.row-->
                        <div class="chart-wrapper mt-4">
                            
                                <a href="https://twitter.com/ensgsi?lang=fr">
                                    <img class="align-self-center  mr-3" style="width:700px; height:500px;" alt="" src="{%  static 'Board\assets\img\figure.JPG'%}">
                                </a>
                        </div>
          
                    </div>
                 
                </div>
            </div>
          
          

   
          
          
          
          
          
 
          
          
          


































                <!-- /# card -->
            </div>


        </div> <!-- .content -->
    </div><!-- /#right-panel -->

    <!-- Right Panel -->

    <script src="{%  static 'Students/Dashboard/vendors/jquery/dist/jquery.min.js'%}"></script>
    <script src="{%  static 'Students/Dashboard/vendors/popper.js/dist/umd/popper.min.js'%}"></script>
    <script src="{%  static 'Students/Dashboard/vendors/bootstrap/dist/js/bootstrap.min.js'%}"></script>
    <script src="{%  static 'Students/Dashboard/assets/js/main.js'%}"></script>


    <script src="{%  static 'Students/Dashboard/vendors/chart.js/dist/Chart.bundle.min.js'%}"></script>
    <script src="{%  static 'Students/Dashboard/assets/js/dashboard.js'%}"></script>
    <script src="{%  static 'Students/Dashboard/assets/js/widgets.js'%}"></script>
    <script src="{%  static 'Students/Dashboard/vendors/jqvmap/dist/jquery.vmap.min.js'%}"></script>
    <script src="{%  static 'Students/Dashboard/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js'%}"></script>
    <script src="{%  static 'Students/Dashboard/vendors/jqvmap/dist/maps/jquery.vmap.world.js'%}"></script>
    <script>
        (function($) {
            "use strict";

            jQuery('#vmap').vectorMap({
                map: 'world_en',
                backgroundColor: null,
                color: '#ffffff',
                hoverOpacity: 0.7,
                selectedColor: '#006400',
                enableZoom: true,
                showTooltip: true,
                values: sample_data,
                scaleColors: ['#006400', '#3CB371'],
                normalizeFunction: 'polynomial'
            });
        })(jQuery);
    </script>

</body>

</html>

stories/templates/classroom/teachers/question_add_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="">My Quizzes</a></li>
      <li class="breadcrumb-item"><a href="">{{ quiz.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Add a new question</li>
    </ol>
  </nav>
  <h2 class="mb-3">Add a new question</h2>
  <p class="lead">Add first the text of the question. In the next step you will be able to add the possible answers.</p>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Save</button>
    <a href="" class="btn btn-outline-secondary" role="button">Nevermind</a>
  </form>
{% endblock %}