innovation/urls.py
from django.urls import include, path
from django.conf import settings
from stories.views import classroom, students, teachers
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext


urlpatterns = [
    
 
   
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns( # < here
    path('', include('stories.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', classroom.SignUpView.as_view(), name ='signup'),
    path('accounts/signup/student/', students.StudentSignUpView.as_view(), name ='student_signup'),
    path('accounts/signup/teacher/', teachers.TeacherSignUpView.as_view(), name='teacher_signup'),
    path('djrichtextfield/', include('djrichtextfield.urls')),
    
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stories/urls.py
from django.urls import include, path
from .views import classroom, students, teachers



urlpatterns = [
    path('', classroom.home, name='home'),
    path('Innovtion/', classroom.Introduction, name='Introduction'),
    path('Stories/', classroom.Stories, name='Stories'),
    path('Research/', classroom.Research, name='Research'),
    path('teachers/', include(([
        path('', teachers.TeachersListView.as_view(), name='stories_list'),
        path('studies/tables/', teachers.TableListView.as_view(), name='table_list'),
        path('comments/<int:pk>/', teachers.EvaluerlistView, name='comment_list'),
        path('case/<int:pk>/', teachers.take_quiz, name='take_quiz'),
         path('case/Remove/<int:pk>/', teachers.DeleteView, name='delete_quiz'),
        path('story/<int:pk>/', teachers.publi_quiz, name='publi_quiz'),
        path('studies/', teachers.modifaction, name='modif_quiz'),
        path('board/terms/', teachers.TermsListView.as_view(), name='terms_teacher_list'),
       
   
        

        
#<int:pk>/

    ], 'stories'), namespace='teachers')),

   path('students/', include(([    
        path('', students.HomeListView.as_view(), name='students_home'),
        path('board/', students.StudiesListView.as_view(), name='students_borad'),
        path('board/contenu', students.contenuListView.as_view(), name='students_contenu'),
        path('board/enjeu', students.enjeuListView.as_view(), name='students_enjeu'),
        path('board/comite', students.comiteListView.as_view(), name='students_comite'),
        path('board/exemple', students.exempleListView.as_view(), name='students_exemple'),
        path('board/tables/', students.TableListView.as_view(), name='table_list'),
        path('board/dates/', students.DatesListView.as_view(), name='dates_list'),
        path('board/information/', students.InfoListView.as_view(), name='info_list'),
        path('board/terms/', students.TermsListView.as_view(), name='terms_list'),
        path('case/add/', students.CaseCreateView.as_view(), name='case_add'),
        path('case/<int:pk>/change', students.CaseUpdateView.as_view(), name='case_change'),
        path('case/<int:pk>/delete/', students.QuizDeleteView.as_view(), name='case_delete'),
        path('case/<int:pk>/display', students.post_detail, name='post_detail'),
        path('case/<int:pk>/evaluation', students.evaluation_quiz, name='evalu_detail'),
        ], 'stories'), namespace='students')),

]

stories/views/classroom.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView
from django.utils import timezone
from django.utils.translation import ugettext
from ..models import Cases, Student, User, School
from  stories.filters import CasesFilter


class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


def home(request):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            return redirect('teachers:stories_list')
        else:
            return redirect('students:students_borad')
    return render(request, 'classroom/home.html')


    
def Introduction(request):
     template_name = 'classroom/Introduction.html'
     return render(request, template_name)



def Research(request):
     case_list = Cases.objects.all()
     case_filter = CasesFilter(request.GET, queryset = case_list)
     template_name = 'classroom/research.html'
     return render(request, template_name, {'filter' : case_filter})



def Stories(request):
     posts = Cases.objects.filter(created_date__lte=timezone.now()).order_by('created_date')
     return render(request, 'classroom/stories.html', {'posts':posts})

stories/views/students.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from ..decorators import student_required
from ..forms import  StudentSignUpForm, GroupForm
from ..models import Cases, Student, User, School, Comment, SummaryHistory
from django.utils.translation import ugettext
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.http import Http404



class StudentSignUpView(CreateView):
    model = User
    form_class = StudentSignUpForm
    template_name = 'registration/student_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'student'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('students:students_borad')



class HomeListView(ListView):
    model = Cases
    ordering = ('title_case', )
    context_object_name = 'cases'
    template_name = 'classroom/students/index.html'

@method_decorator([login_required, student_required], name='dispatch')
class StudiesListView(ListView):
    model = Cases
    ordering = ('title_case', )
    context_object_name = 'cases'
    template_name = 'classroom/students/board/index.html'



@method_decorator([login_required, student_required], name='dispatch')
class TableListView(ListView):
    model = Cases
    ordering = ('title_case', )
    context_object_name = 'cases'
    template_name = 'classroom/students/board/tables-basic.html'

    def get_queryset(self):
        queryset = self.request.user.cases \
            .select_related('school_case') 
        return queryset


@method_decorator([login_required, student_required], name='dispatch')
class DatesListView(ListView):
    model = School
    context_object_name = 'cases'
    template_name ='classroom/students/board/dates.html'
    
    def get_queryset(self):
        queryset = self.request.user.student.school\
            .prefetch_related('students_school') 
        return queryset


@method_decorator([login_required, student_required], name='dispatch')
class InfoListView(ListView):
    model = School
    context_object_name = 'cases'
    template_name ='classroom/students/board/information.html'
    
 
@method_decorator([login_required, student_required], name='dispatch')
class TermsListView(ListView):
    model = School
    context_object_name = 'cases'
    template_name ='classroom/students/board/terms.html'



@method_decorator([login_required, student_required], name='dispatch')
class CaseCreateView(CreateView):
    model = Cases
    fields = ('title_case', 'subject',  'produit', 'mois', 'image_produit', 'date', 'context', 'context_images', 'description', 'description_shema',  'diagnostic',  'diagnostic_shema',  'processus',  'processus_shema',  'reference', 'abstract', 'auteur', 'school_case', 'terms_and_conditions')
    template_name = 'classroom/students/board/forms-basic.html'
    #case_add_form

    def form_valid(self, form):
        case = form.save(commit=False)
        case.owner = self.request.user
        case.save()
        return redirect('students:case_change', case.pk)


@method_decorator([login_required, student_required], name='dispatch')
class CaseUpdateView(UpdateView):
    model = Cases
    fields = fields = ('title_case', 'subject', 'produit', 'mois', 'image_produit', 'date', 'context', 'context_images', 'description', 'description_shema',  'diagnostic',  'diagnostic_shema',  'processus',  'processus_shema',  'reference', 'abstract', 'auteur', 'school_case', 'terms_and_conditions')
    context_object_name = 'case'
    template_name = 'classroom/students/case_change_form.html'
    
    def get_queryset(self):
        '''
        This method is an implicit object-level permission management
        This view will only match the ids of existing quizzes that belongs
        to the logged in user.
        '''
        return self.request.user.cases.all()
 
    def form_valid(self, form):
        case = form.save(commit=False)
        case.update_date = timezone.now()
        case.save()
        return redirect('students:case_change', case.pk)


        



@method_decorator([login_required, student_required], name='dispatch')
class QuizDeleteView(DeleteView):
    model = Cases
    context_object_name = 'case'
    template_name = 'classroom/students/case_delete_confirm.html'
    success_url = reverse_lazy('students:table_list')

    def delete(self, request, *args, **kwargs):
        quiz = self.get_object()
        messages.success(request, 'The quiz %s was deleted with success!' % quiz.title_case)
        return super().delete(request, *args, **kwargs)

    def get_queryset(self):
        return self.request.user.cases.all()







def post_detail(request, pk):
    post = get_object_or_404(Cases, pk=pk)
    return render(request, 'classroom/home/landing.html', {'post': post})
    
    #return render(request, 'classroom/students/case_form_display.html', {'post': post})
    


@login_required
@student_required
def evaluation_quiz(request, pk):
    try:
        quiz = get_object_or_404(Cases, pk=pk)
        Comments = Comment.objects.filter(case__pk= quiz.pk).order_by('date_comment')
    except Comment.DoesNotExist:
            raise Http404('cases does not exist')

    return render(request, 'classroom/students/board/evaluation_resultat.html', {'Comments': Comments}  )



@method_decorator([login_required, student_required], name='dispatch')
class contenuListView(ListView):
    model = Cases
    ordering = ('title_case', )
    context_object_name = 'cases'
    template_name = 'classroom/students/board/contenu.html'


@method_decorator([login_required, student_required], name='dispatch')
class enjeuListView(ListView):
    model = Cases
    ordering = ('title_case', )
    context_object_name = 'cases'
    template_name = 'classroom/students/board/enjeu.html'



@method_decorator([login_required, student_required], name='dispatch')
class comiteListView(ListView):
    model = Cases
    ordering = ('title_case', )
    context_object_name = 'cases'
    template_name = 'classroom/students/board/comite.html'




@method_decorator([login_required, student_required], name='dispatch')
class exempleListView(ListView):
    model = Cases
    ordering = ('title_case', )
    context_object_name = 'cases'
    template_name = 'classroom/students/board/exemple.html'

stories/views/teachers.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Avg, Count
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from ..decorators import teacher_required
from ..models import Cases, Teacher, School, User,  Comment, SummaryHistory, Case_publ
from django.views.generic import CreateView, ListView, UpdateView
from ..forms import  TeacherSignUpForm, CommentForm, StorieForm, pubForm
from django.http import HttpResponse
from django.template import loader
from django.http import Http404
from django.utils.translation import ugettext
from django.shortcuts import render
from django.http import HttpResponseRedirect



class TeacherSignUpView(CreateView):
    model = User
    form_class = TeacherSignUpForm
    template_name = 'registration/signup_form_teacher.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'teacher'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('teachers:stories_list')



@method_decorator([login_required, teacher_required], name='dispatch')
class TeachersListView(ListView):
    model = Cases
    ordering = ('title_case', )
    context_object_name = 'cases'
    template_name = 'classroom/teachers/board/index.html'


    

@method_decorator([login_required, teacher_required], name='dispatch')
class TermsListView(ListView):
    model = Cases
    ordering = ('title_case', )
    context_object_name = 'cases'
    template_name = 'classroom/teachers/board/terms_teacher.html'





@method_decorator([login_required, teacher_required], name='dispatch')
class TableListView(ListView):
    model = Cases
    ordering = ('title_case', )
    context_object_name = 'cases'
    template_name = 'classroom/teachers/board/tables-basic.html'

    def get_queryset(self):
        teacher = self.request.user.teacher
        teacher_schools = teacher.school.values_list('pk', flat=True)
        # taken_quizzes = student.quizzes.values_list('pk', flat=True)
        queryset = Cases.objects.filter(school_case__in = teacher_schools) 
        return queryset





@login_required
@teacher_required
def publication(request, pk):
    quiz = get_object_or_404(Cases, pk=pk)
    teacher = request.user.teacher
    template_name = 'registration/signup_form_teacher.html'


    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.case= quiz
            post.save()
            return redirect('teachers:take_quiz', quiz.pk)
  


def EvaluerlistView(request, pk):
    try:
        comment = get_object_or_404(Comment, pk=pk)
    except Comment.DoesNotExist:
            raise Http404('cases does not exist')

    return render(request, 'classroom/teachers/board/takens.html', {'comment': comment}  )


@login_required
@teacher_required
def take_quiz(request, pk):
    quiz = get_object_or_404(Cases, pk=pk)
    teacher = request.user.teacher
    template_name = 'registration/signup_form_teacher.html'

    try:

        summary_history = SummaryHistory.objects.filter(case__pk= quiz.pk).order_by('-version')
    except summary_history.DoesNotExist:
            raise Http404('cases does not exist')

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.case= quiz
            post.owner = request.user
            post.save()
            return redirect('teachers:take_quiz', quiz.pk)
    else:

        form = CommentForm()
        try:
            quiz = get_object_or_404(Cases, pk=pk)
            Comments = Comment.objects.filter(case__pk= quiz.pk).order_by('date_comment')
        except Comment.DoesNotExist:
               raise Http404('cases does not exist')

    return render(request, 'classroom/teachers/board/forms.html', {'form': form, 'quiz':quiz, 'Comments': Comments, 'summary_history': summary_history})




@login_required
@teacher_required
def modifaction(request, pk):
    try:
        quiz = get_object_or_404(Cases, pk=pk)
        summary_history = SummaryHistory.objects.filter(case__pk= quiz.pk).order_by('-version')
    except summary_history.DoesNotExist:
            raise Http404('cases does not exist')

    return render(request, 'classroom/teachers/board/tables-basic.html', {'summary_history': summary_history}  )



@method_decorator([login_required, teacher_required], name='dispatch')
class DatesListView(ListView):
    model = School
    context_object_name = 'cases'
    template_name ='classroom/teachers/board/dates.html'
    
    def get_queryset(self):
        queryset = self.request.user.teacher.school\
            .prefetch_related('teacher_school') 
        return queryset



@login_required
@teacher_required
def DeleteView(request, pk):
    try:
           quiz = get_object_or_404(Cases, pk=pk).delete()
    except quiz.DoesNotExist:
            raise Http404('cases does not exist')

    return render(request, 'classroom/teachers/board/tables-basic.html' )




@login_required
@teacher_required
def publi_quiz(request, pk):
    quiz = get_object_or_404(Cases, pk=pk)
    
    try:
           newSummary = Case_publ(case_publ=quiz)
           newSummary.save()
    except quiz.DoesNotExist:
            raise Http404('cases does not exist')

    return render(request, 'classroom/teachers/board/index.html' )






           



    

stories/templates/classroom/recherche.html
{% extends 'base.html' %}

{% block content %}
  <form method="get">
    {{ filter.form.as_p }}
    <button type="submit">Search</button>
  </form>
  <ul>
  {% for user in filter.qs %}
    <li>{{ user.name }} - {{ user.abstract }}</li>
  {% endfor %}
  </ul>
{% endblock %}

stories/templates/classroom/research.html
{%load static%}
{% load i18n %}

<!DOCTYPE html>
<html lang="en-US" dir="ltr">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- ===============================================-->
    <!--    Document Title-->
    <!-- ===============================================-->
    <title>Innovation Stories</title>


    <!-- ===============================================-->
    <!--    Favicons-->
    <!-- ===============================================-->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'Board/assets/img/favicons/apple-touch-icon.png'%}'%}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'Board/assets/img/favicons/favicon-32x32.png'%}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'Board/assets/img/favicons/favicon-16x16.png'%}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'Board/assets/img/favicons/favicon.ico'%}">
    <link rel="manifest" href="{% static 'Board/assets/img/favicons/manifest.json'%}">
    <meta name="msapplication-TileImage" content="{% static 'Board/assets/img/favicons/mstile-150x150.png'%}">
    <meta name="theme-color" content="#ffffff">


    <!-- ===============================================-->
    <!--    Stylesheets-->
    <!-- ===============================================-->
    <link href="{% static 'Board/assets/lib/prismjs/prism.css'%}" rel="stylesheet">
    <link href="{% static 'Board/assets/lib/loaders.css/loaders.min.css'%}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,300,400,500,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
    <link href="{% static 'Board/assets/lib/remodal/remodal.css'%}" rel="stylesheet">
    <link href="{% static 'Board/assets/lib/remodal/remodal-default-theme.css'%}" rel="stylesheet">
    <link href="{% static 'Board/assets/lib/owl.carousel/owl.carousel.css'%}" rel="stylesheet">
    <link href="{% static 'Board/assets/lib/lightbox2/css/lightbox.css'%}" rel="stylesheet">
    <link href="{% static 'Board/assets/lib/semantic-ui-accordion/accordion.min.css'%}" rel="stylesheet">
    <link href="{% static 'Board/assets/lib/semantic-ui-transition/transition.min.css'%}" rel="stylesheet">
    <link href="{% static 'Board/assets/css/theme.css'%}" rel="stylesheet">

  </head>


  <body>

    <!-- ===============================================-->
    <!--    Main Content-->
    <!-- ===============================================-->
   
    
       


              <div class="row no-gutters minh-100vh">
                <div class="col-lg-9 order-1 order-lg-0 page-content pt-6 pt-lg-0">
      
      
                  <!-- ============================================-->
                  <!-- <section> begin ============================-->
                  <section class="pt-5 pt-xl-7 pt-xxl-8">    
                    <div class="container-fluid">
                      <div class="row justify-content-center">
                        <div class="col-lg-10">
                          <div class="text-center mb-5 mb-lg-6">
                            <h2 class="fs-2 fs-sm-3"> <span class="font-weight-medium">Discover innovative </span> Case Studies</h2>
                            <hr class="hr-ornate" />
                            <div class="col-sm-6 col-md-4 col-lg-6 col-xl-4 mb-4 mb-xl-0" style="margin: 0 auto;
                            ">
                       <img class="mb-3" src="{% static 'Board/assets/img/icons/coffe.svg' %}" alt="" width="100" style="text-align:center" />
                  
                    
                     </div>
                            <p>Let's uncover the best stories, you can search by Case Study, Process, Subject...</p>

<div>
                            {% load widget_tweaks %}
                              
                            <form method="get">
                                    <div class="well">
                                    <div class="well">
                                     
                                      <div class="row">
                                        <div class="form-group col-sm-4 col-md-3">
                                                <h6 >Story</h6>
                                          {% render_field filter.form.title_case class="form-control" %}
                                          <h4 ></h4>
                                        </div>
                                        <div class="form-group col-sm-4 col-md-3">
                                                <h6 >Process</h6>
                                          {% render_field filter.form.processus class="form-control" %}
                                          <h4 ></h4>
                                        </div>
                                        <div class="form-group col-sm-4 col-md-3">
                                                <h6 >Subject</h6>
                                          {% render_field filter.form.subject class="form-control" %}
                                          <h4 ></h4>
                                        </div>
                                        <div class="form-group col-sm-4 col-md-3">
                                                <h6 >Month</h6>
                                                {% render_field filter.form.mois class="form-control" %}
                                                <h4 ></h4>
                                                <h4 ></h4>
                                              </div>
                                    </div>
                                                
                                    <button type="submit" class="btn btn-primary"><span class="icon-magnifier search-icon"></span>SEARCH<i class="pe-7s-angle-right"></i></button>   
                                

                                        
                                                    </div>
                                      
                                  </form>




                                </div>





                            
                          </div>
                         
                        </div>
                      </div>
                    </div>
                    <!-- end of .container-->
      
                  </section>
                  <!-- <section> close ============================-->
                  <!-- ============================================-->
      
      
      
      
                  <!-- ============================================-->
                  <!-- <section> begin ============================-->
                  <section class="bg-light text-center">
      
                    <div class="container-fluid">
                      <div class="row justify-content-center">
                        <div class="col-lg-10">
                          <div class="mb-5 mb-lg-6">
                            <h2 class="fs-2 fs-sm-3"> <span class="font-weight-medium">Choose </span>Your Case Studies</h2>
                            <hr class="hr-ornate" />
                          </div>
                          <div class="row">
                      

                            {% for user in filter.qs %}

                            <div class="col-sm-6 col-md-4 col-lg-6 col-xl-4 mb-4 mb-lg-0">
                              <div class="rounded border py-6 bg-white">
                                <h3 class="font-weight-regular text-primary">{{ user.title_case }}</h3>
                                <p class="font-weight-regular text-primary" style=" color: black;"></p>
                                <p><strong>{{ user.subject}}</strong></p>
                      
                                <ul class="list-unstyled text-dark my-4">
                                  <li>{{ user.produit }}</li>
                                  <li>{{ user.subject  }}</li>
                                  <li> {{ user.school_case }}</li>
                                  <li >{{ user.auteur}}</li>
                                  
                                </ul>
                                <form action="{% url 'students:post_detail' user.pk %}" method="get" target="_blank">
                                  <button class="btn btn-primary" type="submit">Get Started<span class="fas fa-chevron-right ml-1"></span></button>
                              



                              





                              </form>
                              </div>
                            </div>



                            {% empty %}

                            <p class="text-center">  No data are availbe about this Case Study</p>   
                                     
                              
        
        
                               {% endfor %}

                          </div>
                        </div>
                      </div>
                    </div>
                    <!-- end of .container-->
      
                  </section>
                  <!-- <section> close ============================-->
                  <!-- ============================================-->
      
      
      
      
                  <!-- ============================================-->
                  <!-- <section> begin ============================-->
                 
                  <!-- <section> close ============================-->
                  <!-- ============================================-->
      
      
                  <footer class="page-footer">
                    <div class="bg-holder" style="background-image:url({% static 'Board/assets/img/sidebars/service.jpg'%});background-position: 0 41%; transform: scale(1.1);">
                    </div>
                    <!--/.bg-holder-->
      
                    <div class="row justify-content-center">
                      <div class="col-lg-10">
                        <div class="row align-items-center">
                          <div class="col-lg-6 text-lg-left">
                            <p class="fs--1 text-uppercase ls font-weight-bold mb-0">
                              Copyright &copy; 2019 Innovation Stories.</p>
                          </div>
                     
                        </div>
                      </div>
                    </div>
                  </footer>
                </div>
                <div class="col-lg-3 col-12 t-0 order-0 order-lg-1 position-absolute position-lg-relative">
                  <div class="h-lg-100vh sticky-top py-4 sticky-area"><span class="btn-close"><img class="d-none d-lg-block times" src="{ static 'Board/assets/img/times.svg'%}" width="25" alt=""/><img class="d-lg-none" src="{% static 'Board/assets/img/times-black.svg'%}" width="18" alt=""/></span>
                    <div class="bg-holder" style="background-image:url({% static 'Board/assets/img/sidebars/service.jpg'%});">
                    </div>
                    <!--/.bg-holder-->
      
                    <h1 class="page-title">Innovation Stories</h1>
                  </div>
                </div>
              </div>
            </div>
            <div class="page position-absolute t-0 w-100" id="portfolio">
              <div class="row no-gutters minh-100vh">
                <div class="col-lg-9 order-1 order-lg-0 page-content pt-6 pt-lg-0">
      
      



    <!-- ===============================================-->
    <!--    JavaScripts-->
    <!-- ===============================================-->
    <script src="{% static 'Board/assets/js/jquery.min.js'%}"></script>
    <script src="{% static 'Board/assets/js/popper.min.js'%}"></script>
    <script src="{% static 'Board/assets/js/bootstrap.js'%}"></script>
    <script src="{% static 'Board/assets/js/plugins.js'%}"></script>
    <script src="{% static 'Board/assets/lib/prismjs/prism.js'%}"></script>
    <script src="{% static 'Board/assets/lib/loaders.css/loaders.css.js'%}"></script>
    <script src="{% static 'Board/assets/js/stickyfill.min.js'%}"></script>
    <script src="{% static 'Board/assets/lib/remodal/remodal.js'%}"></script>
    <script src="{% static 'Board/assets/lib/jtap/jquery.tap.js'%}"></script>
    <script src="https://www.google.com/recaptcha/api.js'%}"></script>
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=es6,Array.prototype.includes,CustomEvent,Object.entries,Object.values,URL"></script>
    <script src="{% static 'Board/assets/lib/owl.carousel/owl.carousel.js'%}"></script>
    <script src="{% static 'Board/assets/lib/isotope-layout/isotope.pkgd.min.js'%}"></script>
    <script src="{% static 'Board/assets/lib/isotope-packery/packery-mode.pkgd.min.js'%}"></script>
    <script src="{% static 'Board/assets/lib/lightbox2/js/lightbox.js'%}"></script>
    <script src="{% static 'Board/assets/lib/semantic-ui-accordion/accordion.min.js'%}"></script>
    <script src="{% static 'Board/assets/lib/semantic-ui-transition/transition.min.js'%}"></script>
    <script src="{% static 'Board/assets/js/theme.js'%}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyARdVcREeBK44lIWnv5-iPijKqvlSAVwbw&callback=initMap" async></script>

  </body>

</html>